name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image (for amd64)
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/pandamkt-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pandamkt-backend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/pandamkt-backend:latest
            docker stop pandamkt || true
            docker rm pandamkt || true
            docker run -d -p 80:3000 --name pandamkt ${{ secrets.DOCKER_USERNAME }}/pandamkt-backend:latest
